print("There once was a 🚢 that went to sea.")
print("The name of the 🚢 was the Captain's Creed.")
print("The name of the 👲 was Captain Jack.")
print("He had a crew of 3.")
print("They were looking up and down the 🌊.")
print("Keeping their eyes open for the 🪙.")
print("They had no 🍀 yet so far.")
print("They end up taking a break to eat some 🥩.")
print("They kept their 🦜's on their shoulders.")
print("The crew then fell asleep. They however were caught in a ⛈️.")
print("All of them ended up falling off. They all washed up to 🏖️.")
print("The End.")