print("Presentation: Exploring Huron-Wendat Heritage")
print("Aspects of Huron-Wendat culture:")
print("- Traditional Practices")
print("- Art and Craftsmanship")
print("- Language and Storytelling")
print("- Community Traditions")
print("Date: Wednesday, November 15, 2023")
print("Duration: 60 minutes")
